### ISSUE TITLE
Update fails on a newly generated project

### ISSUE THREAD

**Issue by frafra** [NINAnor/python-template#9]
```
$ copier update --trust
Updating to template version 0.0.1
Obtaining file:///tmp/copier.main.old_copy.vtm35lni
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
[...]
Install precommit
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
Check the log at /home/frafra/.cache/pre-commit/pre-commit.log
Traceback (most recent call last):
  File "/tmp/copier.main.old_copy.vtm35lni/init.py", line 92, in <module>
    setup(initial_branch=args.initial_branch)
  File "/tmp/copier.main.old_copy.vtm35lni/init.py", line 58, in setup
    install_precommit()
  File "/tmp/copier.main.old_copy.vtm35lni/init.py", line 30, in install_precommit
    subprocess.check_call(["pre-commit", "install"])
  File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pre-commit', 'install']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/frafra/.local/bin/copier", line 8, in <module>
    sys.exit(copier_app_run())
             ^^^^^^^^^^^^^^^^
  File "/home/frafra/.local/pipx/venvs/copier/lib64/python3.11/site-packages/plumbum/cli/application.py", line 638, in run
    inst, retcode = subapp.run(argv, exit=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frafra/.local/pipx/venvs/copier/lib64/python3.11/site-packages/plumbum/cli/application.py", line 633, in run
    retcode = inst.main(*tailargs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/frafra/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/cli.py", line 424, in main
    return _handle_exceptions(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frafra/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/cli.py", line 70, in _handle_exceptions
    method()
  File "/home/frafra/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/cli.py", line 414, in inner
    with self._worker(
  File "/home/frafra/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/main.py", line 217, in __exit__
    raise value
  File "/home/frafra/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/cli.py", line 422, in inner
    worker.run_update()
  File "/home/frafra/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/main.py", line 841, in run_update
    self._apply_update()
  File "/home/frafra/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/main.py", line 860, in _apply_update
    with replace(
  File "/home/frafra/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/main.py", line 217, in __exit__
    raise value
  File "/home/frafra/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/main.py", line 869, in _apply_update
    old_worker.run_copy()
  File "/home/frafra/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/main.py", line 774, in run_copy
    self._execute_tasks(self.template.tasks)
  File "/home/frafra/.local/pipx/venvs/copier/lib64/python3.11/site-packages/copier/main.py", line 296, in _execute_tasks
    subprocess.run(task_cmd, shell=use_shell, check=True, env=local.env)
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '. .venv/bin/activate && python3 init.py main python' returned non-zero exit status 1.
```

**Comment by nicokant** [comment]
resolved by 56e84c9834205916509c54b0fce7de01ea80e9f7
